### ISSUE TITLE
Lazy ingestion will process all the versions of a package instead of the specified one.

### ISSUE THREAD

**Issue by cg122** [fasten-project/pypi-tools#14]
When triggering the lazy ingestion from the restapi, the [kafka-filter-pypi](https://github.com/fasten-project/pypi-tools/tree/main/kafka-filter-pypi) will process all the versions of the package. It is not ideal if we have a dedicated deployment for more focused usage.

**Comment by gdrosos** [comment]
That's right, currently PyPI Filter processes all the versions of a requested package that are not stored in the database. We implemented such mechanism in order to store in the Fasten Knowledge Base the whole PyPI Ecosystem, since we were scraping the web to find new releases and we wanted to simultaneously store all the previous releases.

Unfortunately, this approach makes the PyPI ingestion way slower. I agree that we could modify it to process only the specific package version, given that the PyPI pipeline is primarily used through the ingestion mechanism.

**Comment by cg122** [comment]
@gdrosos I have made a change and pull request to only process specific package version in lazy ingestion. Could you please have a look and comment on the changes?
