### ISSUE TITLE
File paths in the MetadataDB different than source paths on disk

### ISSUE THREAD

**Issue by MagielBruntink** [fasten-project/pypi-tools#2]
In the metadata DB file paths are different than expected from directory structure on disk in the `sources` directory, eg. on Monster.

For examples see: https://api.fasten-project.eu/api/pypi/packages/awscli/1.15.53/files

One entry there is:
```
{
id: 6729025,
package_version_id: 173157,
path: "awscli/alias.py",
checksum: null,
created_at: null,
metadata: null
}
```
There is `awscli/` as a prefix in the path. 

However, the directory structure on disk at monster  is different `ls /mnt/fasten/pypi/sources/a/awscli/1.15.53`
<img width="488" alt="image" src="https://user-images.githubusercontent.com/3635696/167437760-abaad14d-ea9e-43f4-aa7f-c65eafb87f05.png">

The `awscli/` directory is not there, the files are present in the top-level directory of the package-version.

Unfortunately, this is a problem for plugins that rely on the source code, like quality analyzer. It can never match results to callables because the file paths are not  the same.

Another example where this problem occurs:
https://api.fasten-project.eu/api/pypi/packages/dimod/0.6.8/files
`ls /mnt/fasten/pypi/sources/d/dimod/0.6.8`
<img width="431" alt="image" src="https://user-images.githubusercontent.com/3635696/167439137-46981c2f-83c0-48e6-b7b2-ea4eada27e34.png">

Then there are also PyPI packages where there is no additional prefix and the directory structure matches on disk, like:
https://api.fasten-project.eu/api/pypi/packages/namesss/0.1.0/files

`ls /mnt/fasten/pypi/pypi/sources/n/namesss/0.1.0`
<img width="484" alt="image" src="https://user-images.githubusercontent.com/3635696/167438697-13bc01b2-a83d-46cc-ab0e-e1d306dd8988.png">

**Comment by gdrosos** [comment]
Hello @MagielBruntink, thanks for the detailed report!

Indeed, on the first two python revisions the `sourcePath` of their files does not match the actual path on the disk. 

I tried to reproduce the issue with the  2 aforementioned example coordinates and surprisingly, the source code was succesfully placed under the directory that the ercg `sourcePath` field is pointing to.

After some investigation, I noticed that the most recent commit in the code (1b1a7d127a0bb903944ed7963c119665b2eb7ddd) changed the source Path of some packages by adding the parent directory. After reverting this commit, I was able to reproduce the issue  in the reported coordinates.

Therefore, I assume that some call graphs on monster have been generated with an outdated version of this tool which did not include the fix on https://github.com/fasten-project/pypi-tools/commit/1b1a7d127a0bb903944ed7963c119665b2eb7ddd, resulting in this issue.

In order to fix this issue, I am thinking of 3 sollutions:

1. We could redeploy the python pipeline on monster, which is an expensive and time consuming action for this moment.
2. I could create a corrective tool that would identify those coordinates, perform the check introduced in the commit and fix the directories. The coordinates that have their source code in wrong paths are the ones that have an `__init__.py` file in their base directory on monster. 
3.  Lastly, a "lazy" fix would be to adapt the downstream analyzers  to this issue: If the sourcePath does not exist, the analyzers could remove from the string path  the package name and retry their search in the "modified" path in order to retrieve the files from the disk.

Personally, I am leaning heavily towards the second sollution because it seems more clean and efficient. What is your opinion?

**Comment by MagielBruntink** [comment]
Hi @gdrosos just to check that we are on the same page: the issue is with the `path` values in the `files` table on the DB; those do not match the actual source directories on disk. Do you propose to correct those values in the DB?

**Comment by gdrosos** [comment]
> Hi @gdrosos just to check that we are on the same page: the issue is with the `path` values in the `files` table on the DB; those do not match the actual source directories on disk. Do you propose to correct those values in the DB?

Hi, the path values in the files table in the db actually refer to the correct directory. The error is that the source code of some packages is on a wrong directory on disk. I propose creating an intermediate tool which would locate those revisions and recreate the source code in the correct directory on the disk so that the path values of the db are correct.

**Comment by MagielBruntink** [comment]
So what you are saying is that the structure on disk should be as follows for the first example:
`/mnt/fasten/pypi/sources/a/awscli/1.15.53/awscli`?

(That is the path inside the container, on the host monster it would even be `/mnt/fasten/pypi/pypi/sources/a/awscli/1.15.53/awscli`)

**Comment by MagielBruntink** [comment]
You are correct. This is the content of the awscli package:
![image](https://user-images.githubusercontent.com/3635696/167808312-7d603c78-be1f-4d2b-ba45-424751dfadca.png)

So somehow during the unpacking of packages directory structure got lost.

This means that we'll have to:
 - Fix these missing directory structures as you suggested in option 2
 - Rerun code quality analysis (because it will have wrong paths in its results)
 - Rerun inserting code quality metrics into the DB

**Comment by gdrosos** [comment]
> So what you are saying is that the structure on disk should be as follows for the first example: `/mnt/fasten/pypi/sources/a/awscli/1.15.53/awscli`?
> 
> (That is the path inside the container, on the host monster it would even be `/mnt/fasten/pypi/pypi/sources/a/awscli/1.15.53/awscli`)

Yes, exactly. On this case the name of the parent directory of the `_init_.py` happens to be the same with the package name, making the path more "ugly" but I guess that this is not the case for all packages.

**Comment by gdrosos** [comment]
> You are correct. This is the content of the awscli package: ![image](https://user-images.githubusercontent.com/3635696/167808312-7d603c78-be1f-4d2b-ba45-424751dfadca.png)
> 
> So somehow during the unpacking of packages directory structure got lost.
> 
> This means that we'll have to:
> 
> * Fix these missing directory structures as you suggested in option 2
> * Rerun code quality analysis (because it will have wrong paths in its results)
> * Rerun inserting code quality metrics into the DB

Yes, would it be expensive to  Rerun the code quality analysis ?

**Comment by MagielBruntink** [comment]
It was actually in progress, I think maybe it did 20% so far. We could rerun without too much issue I think. The metadata out topic for Python has only 3 partitions though, which limits concurrency. If we could stream it first into a 96 partitions topic we could redo the quality analysis faster. 

Also I observed that many old messages are still in that topic. Do you know at what offset the most up-to-date messages are listed from?

**Comment by gdrosos** [comment]
Yes, we could increase the number of partitions of the `fasten.MetadataDBPythonExtension.out` topic.

Regarding the second question, unfortunately not. Is this blocker? (meaning that we have to repopulate the db and producing the output in a new topic) Or  is it possible to consume only the  555099 most recent kafka messages? (Since this is the number of revision entries that we have on the db).

**Comment by MagielBruntink** [comment]
It’s not a blocker but it will take longer. I will create a new topic with a lot of partitions. In general for topics that need further processing I think they should have 96 partitions. If you increase the number now it will work but messages will stay in their current partitions. Only new ones will be distributed. But with a tool I can stream all into a new topic.

**Comment by gdrosos** [comment]
Great! So from my side, I will start working on developing the tool which would correct the aforementioned issue. If it helps I could produce to a new output topic all the pypi coords whose  source code directory will be modified.

**Comment by MagielBruntink** [comment]
That will be useful to keep track I think.

**Comment by MagielBruntink** [comment]
There is a new 96-partition topic `fasten.MetadataDBPythonExtension.rebalanced.out` that I will be using to re-do the quality analysis run. Please let me know when I should kick that off!

**Comment by gdrosos** [comment]
Hello @MagielBruntink , yesterday I deployed the [fixing tool](https://github.com/fasten-project/pypi-tools/tree/fix-source-path/source-path-fixer) on [kubernetes](https://github.com/fasten-project/k8s-deployments/blob/master/fasten/pypi-cg-producer/pypi-path-fixer.yaml).

 Currently it has processed approximatelly 21% of the PyPI coords and fixed the `sourcePath` of 74618  PyPI coordinates. 
 
The tool will need some time  to process all the records because we have many coordinates (more than half a million) and in order to fix the issue our tool moves the source code of the erroneous packages to the correct folder. This operation is expensive for packages with many files, but I expect it to finish in 4 days.

The topic `fasten.pypi.sourcePathFixer.out` holds the  PyPI coords  whose sourcePath was fixed. I have validated this tool by observing the sourcePath of those packages on the disk and it is correct in some sample manual checks.

**Comment by MagielBruntink** [comment]
Hi @gdrosos sounds good! Are you processing from the metadatadbpython topic? If yes I could already start up the quality analysis tool to process the fixed package versions.

**Comment by gdrosos** [comment]
Hello, apparently not, I consume the output topic of pycg (`fasten.pycg.cvt.out`) because it had 96 partitions . As I observed on kafkadrop for some reason the `fasten.MetadataDBPythonExtension.rebalanced.out` topic has 3 partitions instead of 96, which would make the processing slower.

<img width="1026" alt="Screenshot 2022-05-14 at 3 35 14 PM" src="https://user-images.githubusercontent.com/56369797/168425955-28b9d4f1-836e-46b3-80c2-ff9b46aa76db.png">

**Comment by MagielBruntink** [comment]
I must have forgotten to set the partitions…

Are the messages in fasten.pypi.sourcePathFixer.out similar to the ones in fasten.metadatadbpythonextensions.out ?

**Comment by gdrosos** [comment]
> Are the messages in fasten.pypi.sourcePathFixer.out similar to the ones in fasten.metadatadbpythonextensions.out ?

No, in the kafka message, we just track the package name and the version of the coordinate fixed:

```
{
  "plugin_name": "Python Source Path Fixer",
  "product": <packageName>,
  "version": <version>,
  "created_at": <timestamp>
}
```

**Comment by MagielBruntink** [comment]
Ok then I need to wait until it’s all done before I restart the quality analyzers.

**Comment by gdrosos** [comment]
Yeap, currently we have processed approximately 30% of the packages. The fixer may end in less than 4 days actually, it depends on the size of the remaining packages.

**Comment by MagielBruntink** [comment]
Secret performance tip: make sure your pods are running on lima, that's where the /mnt/fasten volume is local. Makes a big difference in I/O performance.

```
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "kubernetes.io/hostname"
                  operator: In
                  values: ["lima"]
```

**Comment by gdrosos** [comment]
Hello @MagielBruntink , thanks for the tip! I am seeing on many k8s deplyoment files that they do not schedule the pods on lima due to permissions bug, will this be a blocker? An example can be found  [here](https://github.com/fasten-project/k8s-deployments/blob/1092ac87cccb96d16d403c1f9c5461c77b89f715/fasten/rapid/rapid-plugin-python.yaml#L42-L49).

**Comment by MagielBruntink** [comment]
Yeah I have seen that too, but never had a problem with it…

**Comment by gdrosos** [comment]
Hello @MagielBruntink , the fixing tool has processed all the PyPI coords, resulting in fixing the path in 287.238 PyPI revisions. Therefore, you can restart the Python Quality Analyzer. Please let me know if you encounter any issue!

**Comment by MagielBruntink** [comment]
Thanks @gdrosos the paths are fixed for the coordinates in this issue, and I'm assuming for the rest too :-) I have restarted the quality analysis plugins and will report how it goes.
